NewMoonSolutions/Controllers/ExampleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace NewMoonSolutions.Controllers
{
    public class ExampleController : Controller
    {
        // GET: Example
        public ActionResult Index()
        {
            return View();
        }

        // GET: Example
        public ActionResult Connection()
        {
            return View();
        }
    }
}

NewMoonSolutions/Controllers/PonyExpressController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace NewMoonSolutions.Controllers
{
    public class PonyExpressController : Controller
    {
        // GET: PonyExpress
        public ActionResult Index()
        {
            return View();
        }
    }
}

NewMoonSolutions/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-164156518-1"></script>
    <script>
        window.dataLayer = window.dataLayer || [];
        function gtag() { dataLayer.push(arguments); }
        gtag('js', new Date());

        gtag('config', 'UA-164156518-1');
    </script>

    <title>@ViewBag.Title - Pony Express Unity Networking Toolkit</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="keywords" content="Unity, Networking, Sockets" />
    <meta name="description" content="Pony Express is a plug-in that adds networking and socket-level communication instantly to Unity.  Pony Express
          allows you to immediately add networked client-server functionality to your Unity application with no extra programming.  Add networking to your
          iOS, Android, Web GL, Unity Web Client, and WinPhone Unity Projects immediately with no extra licenses." />
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    @RenderSection("styles", required: false)

    <script type="text/javascript">
        var appInsights = window.appInsights || function (config) {
            function s(config) { t[config] = function () { var i = arguments; t.queue.push(function () { t[config].apply(t, i) }) } } var t = { config: config }, r = document, f = window, e = "script", o = r.createElement(e), i, u; for (o.src = config.url || "//az416426.vo.msecnd.net/scripts/a/ai.0.js", r.getElementsByTagName(e)[0].parentNode.appendChild(o), t.cookie = r.cookie, t.queue = [], i = ["Event", "Exception", "Metric", "PageView", "Trace"]; i.length;)s("track" + i.pop()); return config.disableExceptionTracking || (i = "onerror", s("_" + i), u = f[i], f[i] = function (config, r, f, e, o) { var s = u && u(config, r, f, e, o); return s !== !0 && t["_" + i](config, r, f, e, o), s }), t
        }({
            instrumentationKey: "f411b8ac-0f79-45bf-8b6c-34f210aafab6"
        });

        window.appInsights = appInsights;
        appInsights.trackPageView();
    </script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("New Moon Legacy", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>
                        <a href="http://newmoonlegacy.com/Home/WebGLDemo">Demo</a>
                    </li>
                    <li>@Html.ActionLink("Pony Express", "Index", "PonyExpress")</li>
                    <li>@Html.ActionLink("Documentation", "Index", "Documentation")</li>
                    <li>@Html.ActionLink("Examples", "Index", "Example")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
        <div class="container body-content">
        <div>
            @RenderBody()
            <hr />
            <footer>
                <p>&copy; @DateTime.Now.Year - New Moon Legacy</p>
            </footer>
        </div>
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>